### ISSUE TITLE
Files fails to open 'Recent' bookmark

### ISSUE THREAD

**Issue by JCatrielLopez** [elementary/files#1483]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
Files sometimes fails to open the 'Recent' bookmark.

### To Reproduce
1. Go to Files.
2. Click on several bookmarks (I haven't been able to reproduce it while clicking on it on first try).
3. Click on 'Recent'.
4. See log

### Logs

```** Message: 15:13:07.394: Application.vala:75: Report any issues/bugs you might find to https://github.com/elementary/files/issues

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:10.277: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): GLib-GObject-CRITICAL **: 15:13:10.712: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:13.022: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): GLib-GObject-CRITICAL **: 15:13:13.488: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:15.675: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): GLib-GObject-CRITICAL **: 15:13:16.029: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:18.468: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): GLib-GObject-CRITICAL **: 15:13:18.755: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:19.471: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:20.589: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): GLib-GObject-CRITICAL **: 15:13:21.156: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:21.523: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:23.433: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:23.759: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): GLib-GObject-CRITICAL **: 15:13:24.608: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:25.388: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:26.731: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed

(io.elementary.files:3582): GLib-GObject-CRITICAL **: 15:13:27.047: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.files:3582): Gtk-CRITICAL **: 15:13:29.674: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed
```

## Platform Information

![Screenshot from 2020-09-25 15-21-41](https://user-images.githubusercontent.com/31131027/94302669-f31e6000-ff42-11ea-9aca-1e21c4471124.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context
Privacy mode is ON. Files sometimes crash too, but I haven't be able to capture the console output as it almost never happens.

**Comment by jeremypw** [comment]
> Files sometimes fails to open the 'Recent' bookmark

Do you mean FIles crashes?  If not, what exactly happens?

I cannot reproduce exactly but I do get a critical terminal warning with the backtrace:
```
#0  0x00007ffff7662ea1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff76641dd in g_logv () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff766431f in g_log () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff73d1c3c in g_object_ref () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff796215c in gof_directory_async_cache_lookup () at /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.4
#5  0x00007ffff7962b33 in gof_directory_async_from_gfile () at /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.4
#6  0x00005555555be8f8 in  ()
#7  0x00005555555befc3 in  ()
#8  0x00005555555af1e4 in marlin_view_view_container_focus_location ()
#9  0x0000555555595128 in marlin_view_window_uri_path_change_request ()
#10 0x00007ffff73cd10d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff73e005e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff73e8715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff73e912f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00005555555b4f21 in  ()
#15 0x00005555555bd396 in  ()
#16 0x00007ffff66827fb in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff73cd10d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff73e005e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff73e80af in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff73e912f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff67ca534 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff667f86e in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff6681948 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff6192765 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#25 0x00007ffff61c2f92 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#26 0x00007ffff765d417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff765d650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff765d6dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff70c0efd in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#30 0x000055555557b617 in _vala_main ()
#31 0x00007ffff4996b97 in __libc_start_main (main=
    0x55555557b490 <main>, argc=1, argv=0x7fffffffde98, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffde88)
    at ../csu/libc-start.c:310
#32 0x000055555557b4ca in _start ()
```
so something is not right.

**Comment by jeremypw** [comment]
I also get the same error with latest unreleased version, running in Odin.

**Comment by JCatrielLopez** [comment]
I meant that it just doesn't open the bookmark.  It _sometimes_ crash, but i haven't been able to reproduce it yet.

**Comment by jeremypw** [comment]
Ah, OK.  I can confirm that it does sometimes not navigate to the Recent view (with no terminal messages) and sometimes does (with critical message as indicated above) so presumably some kind of race condition involved.  Investigating.
