### ISSUE TITLE
files hangs when I copy many files at once and their size together is large

### ISSUE THREAD

**Issue by Fabioulloaev** [elementary/files#1484]
I use Elementary 5.1.7, I have it installed on two computers, on both when I try to copy some files from a removable disk to the laptop with "files" it blocks or sometimes closes leaving the copy halfway. Install Nautilus and had no problem copying files

 gdb io.elementary.files
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
Para las instrucciones de informe de errores, vea:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Leyendo símbolos desde io.elementary.files...(no se encontraron símbolos de depuración)hecho.
(gdb) run
Starting program: /usr/bin/io.elementary.files 
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Nuevo Thread 0x7fffe64b7700 (LWP 6462)]
[Nuevo Thread 0x7fffe5cb6700 (LWP 6463)]
[Nuevo Thread 0x7fffe5074700 (LWP 6464)]
** Message: 16:34:56.989: Application.vala:75: Report any issues/bugs you might find to https://github.com/elementary/files/issues
[Nuevo Thread 0x7fffd7dea700 (LWP 6465)]
[Nuevo Thread 0x7fffcd097700 (LWP 6467)]
[Nuevo Thread 0x7fffcc896700 (LWP 6468)]
[Thread 0x7fffd7dea700 (LWP 6465) terminado]
[Thread 0x7fffcc896700 (LWP 6468) terminado]
[Nuevo Thread 0x7fffcc896700 (LWP 6476)]
[Nuevo Thread 0x7fffd7dea700 (LWP 6477)]
[Nuevo Thread 0x7fffc73bd700 (LWP 6478)]
[Nuevo Thread 0x7fffc6bbc700 (LWP 6479)]
[Nuevo Thread 0x7fffc63bb700 (LWP 6480)]
[Nuevo Thread 0x7fffc5bba700 (LWP 6481)]
[Thread 0x7fffc6bbc700 (LWP 6479) terminado]
[Thread 0x7fffcd097700 (LWP 6467) terminado]
[Thread 0x7fffc5bba700 (LWP 6481) terminado]
[Thread 0x7fffc63bb700 (LWP 6480) terminado]
[Thread 0x7fffc73bd700 (LWP 6478) terminado]
[Thread 0x7fffd7dea700 (LWP 6477) terminado]
[Nuevo Thread 0x7fffd7dea700 (LWP 6484)]

** (io.elementary.files:6458): WARNING **: 16:35:07.375: plugin.vala:103: GIT PLUGIN: excluded filesystem type fuse
[Nuevo Thread 0x7fffc73bd700 (LWP 6485)]
[Nuevo Thread 0x7fffc63bb700 (LWP 6486)]
[Nuevo Thread 0x7fffc5bba700 (LWP 6487)]
[Nuevo Thread 0x7fffc6bbc700 (LWP 6488)]
[Nuevo Thread 0x7fffc53b9700 (LWP 6489)]
[Nuevo Thread 0x7fffc4bb8700 (LWP 6490)]
[Nuevo Thread 0x7fffb3fff700 (LWP 6491)]
[Nuevo Thread 0x7fffb37fe700 (LWP 6492)]
[Nuevo Thread 0x7fffb2ffd700 (LWP 6493)]
[Thread 0x7fffb37fe700 (LWP 6492) terminado]
[Thread 0x7fffb3fff700 (LWP 6491) terminado]
[Thread 0x7fffb2ffd700 (LWP 6493) terminado]
[Thread 0x7fffd7dea700 (LWP 6484) terminado]
[Thread 0x7fffc73bd700 (LWP 6485) terminado]
[Thread 0x7fffcc896700 (LWP 6476) terminado]
[Nuevo Thread 0x7fffcc896700 (LWP 6494)]
[Thread 0x7fffcc896700 (LWP 6494) terminado]
[Nuevo Thread 0x7fffcc896700 (LWP 6497)]
[Nuevo Thread 0x7fffc73bd700 (LWP 6498)]
[Thread 0x7fffc73bd700 (LWP 6498) terminado]
[Nuevo Thread 0x7fffc73bd700 (LWP 6499)]
[Nuevo Thread 0x7fffd7dea700 (LWP 6500)]
[Thread 0x7fffcc896700 (LWP 6497) terminado]
[Thread 0x7fffd7dea700 (LWP 6500) terminado]
[Thread 0x7fffc73bd700 (LWP 6499) terminado]
*** BUG ***
In pixman_op: The expression r1 != r1_end was false
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_op: The expression r1 != r1_end was false
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region_append_non_o: The expression y1 < y2 was false
Set a breakpoint on '_pixman_log_error' to debug

Thread 20 "pool" received signal SIGSEGV, Segmentation fault.
[Cambiando a Thread 0x7fffc4bb8700 (LWP 6490)]
__memmove_sse2_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:486
486	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No existe el archivo o el directorio.
(gdb) backtrace
#0  0x00007ffff4a307dd in __memmove_sse2_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:486
#1  0x00007ffff00795f8 in  ()
    at /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
#2  0x00007ffff007b099 in pixman_region32_union ()
    at /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
#3  0x00007ffff5c55140 in cairo_region_union ()
    at /usr/lib/x86_64-linux-gnu/libcairo.so.2
#4  0x00007ffff61aac7b in  ()
    at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007ffff67cb1d2 in gtk_widget_queue_draw_area ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff67d25ad in gtk_widget_queue_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff67d2988 in gtk_widget_queue_resize ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff666cb1e in  ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff666d643 in gtk_label_set_label ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff73d4bae in g_object_setv ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff73d5b3e in g_object_set_property ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff73c8bd7 in  ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff73cd10d in g_closure_invoke ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff73e005e in  ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
---Type <return> to continue, or q <return> to quit---return
#15 0x00007ffff73e8715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff73e912f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff73d15c4 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff73d3b09 in g_object_notify_by_pspec () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff7967583 in pf_progress_info_take_status () at /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.4
#20 0x00007ffff797afd9 in  () at /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.4
#21 0x00007ffff706ea38 in g_file_copy () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#22 0x00007ffff797dd24 in  () at /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.4
#23 0x00007ffff797de80 in  () at /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.4
#24 0x00007ffff797de80 in  () at /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.4
#25 0x00007ffff797f0ae in  () at /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.4
#26 0x00007ffff7084306 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#27 0x00007ffff70abdb6 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#28 0x00007ffff7685b40 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff7685175 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff3b2a6db in start_thread (arg=0x7fffc4bb8700) at pthread_create.c:463
#31 0x00007ffff4a96a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)

**Comment by marco4mp** [comment]
Hi @Fabioulloaev . Are you currently using elementary 6? Do you still have this problem?

**Comment by jeremypw** [comment]
Closing as there was no feedback as to whether the issue occurs on latest version.  Please feel free to raise a new issue relation to the latest version of Files.
