### ISSUE TITLE
Files crash after selecting grid view from column view

### ISSUE THREAD

**Issue by selwynorren** [elementary/files#1695]
## What Happened
When swapping different views everything seems fine, however after selecting grid view, clicking on home and clicking any folder in the first column. Then clicking back to grid view causes files to crash and close.

## Expected Behavior
Grid view will be shown

## Steps to Reproduce
1. Launch Files
2. Click on column view
3. Select home
4. Click any of the home folders to show contents in second pane
5. Click grid view

### Logs
** Message: 00:57:25.726: Application.vala:133: Report any issues/bugs you might find to https://github.com/elementary/files/issues

(io.elementary.files:20448): GLib-GIO-CRITICAL **: 00:57:32.714: g_file_get_uri: assertion 'G_IS_FILE (file)' failed

** (io.elementary.files:20448): CRITICAL **: 00:57:32.714: pf_file_utils_escape_uri: assertion 'uri != NULL' failed

(io.elementary.files:20448): GLib-CRITICAL **: 00:57:32.714: g_uri_parse_scheme: assertion 'uri != NULL' failed
Segmentation fault

## Platform Information
Elementary OS 6 Beta with updates

**Comment by tintou** [comment]
I don't get a crash here, can you try providing us a screencast if the content of the folders aren't too sensitive?

Another way (that might be even better) would be to provide a backtrace of your issue.
Here are the steps:
1. Modify `/etc/apt/sources.list.d/elementary.list` and add `main/debug` on the end of the first line so it looks like this `deb http://ppa.launchpad.net/elementary-os/daily/ubuntu focal main main/debug`
2. Run `sudo apt update`
3. Install debug packages with `sudo apt install systemd-coredump gdb libpantheon-files-core0-dbgsym libpantheon-files-widgets0-dbgsym pantheon-files-dbgsym libglib2.0-0-dbgsym libgtk-3-0-dbgsym`
4. Make the application crash
5. Run `sudo coredumpctl debug /usr/bin/io.elementary.files` and paste the output here :slightly_smiling_face:

**Comment by selwynorren** [comment]
Hello @tintou,

Thanks for your feedback. From what I can see it is when there is no contents of a folder, that this happens. I have created some screen recording of this, as well as the alternate solution you have suggested.

You will see in my recording, I show all the empty folders, these crash as I initially mentioned. In some random use case it defaults to some wierd view, however you will see this in the video (I am not really sure how to describe it)

When I try and install the packages you requested, I get the following error:
`~$ sudo apt install systemd-coredump gdb libpantheon-files-core0-dbgsym libpantheon-files-widgets0-dbgsym pantheon-files-dbgsym libglib2.0-0-dbgsym libgtk-3-0-dbgsym`
`Reading package lists... Done`
`Building dependency tree       `
`Reading state information... Done`
`E: Unable to locate package libglib2.0-0-dbgsym`
`E: Couldn't find any package by glob 'libglib2.0-0-dbgsym`
`E: Unable to locate package libgtk-3-0-dbgsym`


So everything was installed except for `libglib2.0-0-dbgsym libgtk-3-0-dbgsym`

Here is the output received:
           PID: 11567 (io.elementary.f)
           UID: 1000 (selwynorren)
           GID: 1000 (selwynorren)
        Signal: 11 (SEGV)
     Timestamp: Sat 2021-05-08 15:05:36 UTC (10s ago)
  Command Line: io.elementary.files
    Executable: /usr/bin/io.elementary.files
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (selwynorren)
       Boot ID: 7ae4f1e6f9174b78a59122852a010514
    Machine ID: 162b2f9c680c51f5186d97b760964aea
      Hostname: W150HNM-W170HN-0d0f9204
       Storage: /var/lib/systemd/coredump/core.io\x2eelementary\x2ef.1000.7ae4f1e6f9174b78a59122852a010514.11567.1620486336000000000000.lz4
       Message: Process 11567 (io.elementary.f) of user 1000 dumped core.
                
                Stack trace of thread 11567:
                #0  0x00007f1816bc9200 g_type_check_instance_is_a (libgobject-2.0.so.0 + 0x3c200)
                #1  0x00007f1816a0fd43 g_file_get_uri (libgio-2.0.so.0 + 0x63d43)
                #2  0x00005627d10aea81 files_view_view_container_refresh_slot_info (io.elementary.files + 0x63a81)
                #3  0x00005627d10aebe1 files_view_view_container_directory_is_loading (io.elementary.files + 0x63be1)
                #4  0x00005627d10af1f4 files_view_view_container_add_view (io.elementary.files + 0x641f4)
                #5  0x00005627d10af6d8 files_view_view_container_change_view_mode (io.elementary.files + 0x646d8)
                #6  0x00007f1816ba1802 g_closure_invoke (libgobject-2.0.so.0 + 0x14802)
                #7  0x00007f1816bb5814 n/a (libgobject-2.0.so.0 + 0x28814)
                #8  0x00007f1816bc0bbe g_signal_emit_valist (libgobject-2.0.so.0 + 0x33bbe)
                #9  0x00007f1816bc1b9c g_signal_emit_by_name (libgobject-2.0.so.0 + 0x34b9c)
                #10 0x00007f1816dbd519 __lambda21_ (libpantheon-files-widgets.so.4 + 0x21519)
                #11 0x00007f1816c3fbe8 n/a (libglib-2.0.so.0 + 0x52be8)
                #12 0x00007f1816c3f04e g_main_context_dispatch (libglib-2.0.so.0 + 0x5204e)
                #13 0x00007f1816c3f400 n/a (libglib-2.0.so.0 + 0x52400)
                #14 0x00007f1816c3f4a3 g_main_context_iteration (libglib-2.0.so.0 + 0x524a3)
                #15 0x00007f1816a8efe5 g_application_run (libgio-2.0.so.0 + 0xe2fe5)
                #16 0x00005627d1079f3a _vala_main (io.elementary.files + 0x2ef3a)
                #17 0x00007f1815a620b3 __libc_start_main (libc.so.6 + 0x270b3)
                #18 0x00005627d1079e0e _start (io.elementary.files + 0x2ee0e)
                
                Stack trace of thread 11580:
                #0  0x00007f1815b5689d syscall (libc.so.6 + 0x11b89d)
                #1  0x00007f1816c8c623 g_cond_wait (libglib-2.0.so.0 + 0x9f623)
                #2  0x00007f1816c0f59b n/a (libglib-2.0.so.0 + 0x2259b)
                #3  0x00007f1816c69347 n/a (libglib-2.0.so.0 + 0x7c347)
                #4  0x00007f1816c68ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007f18158a5609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f1815b5d293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 11581:
                #0  0x00007f1815b5689d syscall (libc.so.6 + 0x11b89d)
                #1  0x00007f1816c8c623 g_cond_wait (libglib-2.0.so.0 + 0x9f623)
                #2  0x00007f1816c0f59b n/a (libglib-2.0.so.0 + 0x2259b)
                #3  0x00007f1816c69347 n/a (libglib-2.0.so.0 + 0x7c347)
                #4  0x00007f1816c68ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007f18158a5609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f1815b5d293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 11582:
                #0  0x00007f1815b5689d syscall (libc.so.6 + 0x11b89d)
                #1  0x00007f1816c8c623 g_cond_wait (libglib-2.0.so.0 + 0x9f623)
                #2  0x00007f1816c0f59b n/a (libglib-2.0.so.0 + 0x2259b)
                #3  0x00007f1816c69347 n/a (libglib-2.0.so.0 + 0x7c347)
                #4  0x00007f1816c68ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007f18158a5609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f1815b5d293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 11586:
                #0  0x00007f1815b5689d syscall (libc.so.6 + 0x11b89d)
                #1  0x00007f1816c8c746 g_cond_wait_until (libglib-2.0.so.0 + 0x9f746)
                #2  0x00007f1816c0f581 n/a (libglib-2.0.so.0 + 0x22581)
                #3  0x00007f1816c0fba6 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x22ba6)
                #4  0x00007f1816c69419 n/a (libglib-2.0.so.0 + 0x7c419)
                #5  0x00007f1816c68ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #6  0x00007f18158a5609 start_thread (libpthread.so.0 + 0x9609)
                #7  0x00007f1815b5d293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 11570:
                #0  0x00007f1815b50aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007f1816c3f36e n/a (libglib-2.0.so.0 + 0x5236e)
                #2  0x00007f1816c3f4a3 g_main_context_iteration (libglib-2.0.so.0 + 0x524a3)
                #3  0x00007f1816c3f4f1 n/a (libglib-2.0.so.0 + 0x524f1)
                #4  0x00007f1816c68ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007f18158a5609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f1815b5d293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 11571:
                #0  0x00007f1815b50aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007f1816c3f36e n/a (libglib-2.0.so.0 + 0x5236e)
                #2  0x00007f1816c3f6f3 g_main_loop_run (libglib-2.0.so.0 + 0x526f3)
                #3  0x00007f1816acaf8a n/a (libgio-2.0.so.0 + 0x11ef8a)
                #4  0x00007f1816c68ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007f18158a5609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f1815b5d293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 11573:
                #0  0x00007f1815b50aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007f1816c3f36e n/a (libglib-2.0.so.0 + 0x5236e)
                #2  0x00007f1816c3f4a3 g_main_context_iteration (libglib-2.0.so.0 + 0x524a3)
                #3  0x00007f1816ddc99d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007f1816c68ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007f18158a5609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f1815b5d293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 11579:
                #0  0x00007f1815b5689d syscall (libc.so.6 + 0x11b89d)
                #1  0x00007f1816c8c623 g_cond_wait (libglib-2.0.so.0 + 0x9f623)
                #2  0x00007f1816c0f59b n/a (libglib-2.0.so.0 + 0x2259b)
                #3  0x00007f1816c69347 n/a (libglib-2.0.so.0 + 0x7c347)
                #4  0x00007f1816c68ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007f18158a5609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f1815b5d293 __clone (libc.so.6 + 0x122293)

GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/io.elementary.files...
Reading symbols from /usr/lib/debug/.build-id/60/2a52080d60759971313bb956a985f350cc3822.debug...

warning: core file may not match specified executable file.
[New LWP 11567]
[New LWP 11580]
[New LWP 11581]
[New LWP 11582]
[New LWP 11586]
[New LWP 11570]
[New LWP 11571]
[New LWP 11573]
[New LWP 11579]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `io.elementary.files'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1816bc9200 in g_type_check_instance_is_a () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
[Current thread is 1 (Thread 0x7f18145b1a80 (LWP 11567))]

Here is the link to the video as requested as well
[https://drive.google.com/file/d/1ek53xKEuXRuvxB6vVLq3yEssoesiizd_/view?usp=sharing](url)

**Comment by jeremypw** [comment]
I have confirmed this after creating an Empty folder below ~.

```
#0  0x00007ffff7ba9d32 in g_file_get_uri () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#1  0x00005555555e8dd3 in files_view_view_container_refresh_slot_info (self=0x5555559bedb0, loc=0x55555582d0c0) at ../src/View/ViewContainer.vala:369
#2  0x00005555555e8d16 in files_view_view_container_directory_is_loading (self=0x5555559bedb0, loc=0x55555582d0c0) at ../src/View/ViewContainer.vala:361
#3  0x00005555555e8223 in files_view_view_container_add_view (self=0x5555559bedb0, mode=FILES_VIEW_MODE_ICON, loc=0x55555582d0c0, to_select=0x0, to_select_length1=0) at ../src/View/ViewContainer.vala:264
#4  0x00005555555e838f in files_view_view_container_change_view_mode (self=0x5555559bedb0, mode=FILES_VIEW_MODE_ICON, loc=0x55555582d0c0) at ../src/View/ViewContainer.vala:286
#5  0x00005555555b2731 in files_view_window_action_view_mode (self=0x5555559f0400, action=0x555555948400, param=0x555555f2e2f0) at ../src/View/Window.vala:687
#6  0x00005555555aca26 in _files_view_window_action_view_mode_gsimple_action_activate_callback (action=0x555555948400, parameter=0x555555f2e2f0, self=0x5555559f0400) at ../src/View/Window.vala:27
#7  0x00007ffff7d3b802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7d4f814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff7d5abbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff7d5bb9c in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff7fa1bfa in __lambda21_ (self=0x555555701150) at ../libwidgets/Chrome/ViewSwitcher.vala:60
#12 0x00007ffff7fa1c4c in ___lambda21__gsource_func (self=0x555555701150) at ViewSwitcher.c:199
#13 0x00007ffff7dd9be8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff7dd904e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff7dd9400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff7dd94a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff7c28fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#18 0x0000555555582f5a in _vala_main (args=0x7fffffffdda8, args_length1=1) at ../src/main.vala:26
#19 0x0000555555582fa1 in main (argc=1, argv=0x7fffffffdda8) at ../src/main.vala:16
```

**Comment by jeremypw** [comment]
Looks like recent changes to the TreeModel (and/or File object) has altered the outcome of pre-existing races or reference counting resulting in things being accessed that have already been finalized when changing view mode.  I have a "fix" that stops the crash but the underlying cause is hard to identify.
