### ISSUE TITLE
Multiple Critical print on miller view

### ISSUE THREAD

**Issue by KeurKeur** [elementary/files#1696]
## What Happened

On miller view, clicking on folder display multiple critical print on the terminal.

## Expected Behavior

No critical.

## Steps to Reproduce

1. Click on miller view
2. Click on a folder
3. Re-click on this folder.

### Logs

```
** (io.elementary.files:37890): CRITICAL **: 10:13:57.156: files_directory_get_location: assertion 'self != NULL' failed

** (io.elementary.files:37890): CRITICAL **: 10:13:57.156: files_view_view_container_refresh_slot_info: assertion 'loc != NULL' failed

```

## Platform Information

Elementary OS 6 Beta on gnome-boxes. Tested with pantheon-files from the release and the master.

**Comment by jeremypw** [comment]
Backtrace:

```
** (io.elementary.files:24748): CRITICAL **: 12:33:08.116: files_directory_get_location: assertion 'self != NULL' failed
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "io.elementary.f" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7ddf295 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff7ddf295 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7de0579 in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7de0743 in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7f15f80 in files_directory_get_location (self=0x0) at ../libcore/Directory.vala:41
#4  0x00007ffff7ed5bcd in files_abstract_slot_get_location (self=0x5555561113f0) at ../libcore/AbstractSlot.vala:41
#5  0x00005555555e8973 in files_view_view_container_on_slot_active (self=0x5555559beda0, aslot=0x555555caa330, scroll=1, animate=1) at ../src/View/ViewContainer.vala:326
#6  0x00005555555e8435 in _files_view_view_container_on_slot_active_files_abstract_slot_active (_sender=0x555555caa330, scroll=1, animate=1, self=0x5555559beda0)
    at ../src/View/ViewContainer.vala:308
#7  0x00007ffff7ed5fdd in g_cclosure_user_marshal_VOID__BOOLEAN_BOOLEAN
    (closure=0x555555ec4b50, return_value=0x0, n_param_values=3, param_values=0x7fffffffbed0, invocation_hint=0x7fffffffbe50, marshal_data=0x0)
    at ../libcore/AbstractSlot.vala:21
#8  0x00007ffff7d3b802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff7d4f814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff7d5abbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff7d5bb9c in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00005555555f48f8 in files_view_miller_on_slot_active (self=0x555555caa330, aslot=0x5555561113f0, scroll=1, animate=1) at ../src/View/Miller.vala:336
#13 0x00005555555f3a75 in _files_view_miller_on_slot_active_files_abstract_slot_active (_sender=0x5555561113f0, scroll=1, animate=1, self=0x555555caa330)
    at ../src/View/Miller.vala:256
#14 0x00007ffff7ed5fdd in g_cclosure_user_marshal_VOID__BOOLEAN_BOOLEAN
    (closure=0x55555615de90, return_value=0x0, n_param_values=3, param_values=0x7fffffffc530, invocation_hint=0x7fffffffc4b0, marshal_data=0x0)
    at ../libcore/AbstractSlot.vala:21
#15 0x00007ffff7d3b802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff7d4f814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff7d5abbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff7d5bb9c in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00005555555c8425 in files_abstract_directory_view_set_active_slot (self=0x5555560ae430, scroll=1) at ../src/View/AbstractDirectoryView.vala:516
#20 0x00005555555c833a in files_abstract_directory_view_grab_focus (self=0x5555560ae430) at ../src/View/AbstractDirectoryView.vala:502
#21 0x00005555555e20bc in files_abstract_directory_view_real_cancel (self=0x5555560ae430) at ../src/View/AbstractDirectoryView.vala:3701
#22 0x00005555555ba177 in files_column_view_real_cancel (base=0x5555560ae430) at ../src/View/ColumnView.vala:176
#23 0x00005555555e2164 in files_abstract_directory_view_cancel (self=0x5555560ae430) at ../src/View/AbstractDirectoryView.vala:3700
#24 0x00005555555e2259 in files_abstract_directory_view_close (self=0x5555560ae430) at ../src/View/AbstractDirectoryView.vala:3717
#25 0x00005555555efed6 in files_view_slot_real_close (base=0x5555561113f0) at ../src/View/Slot.vala:391
#26 0x00007ffff7ed5432 in files_abstract_slot_close (self=0x5555561113f0) at ../libcore/AbstractSlot.vala:105
#27 0x00005555555f273f in __lambda76_ (_data37_=0x555555805180, s=0x5555561113f0) at ../src/View/Miller.vala:146
#28 0x00005555555f277b in ___lambda76__gfunc (data=0x5555561113f0, self=0x555555805180) at ../src/View/Miller.vala:144
#29 0x00007ffff7dd4d50 in g_list_foreach () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00005555555f28db in files_view_miller_truncate_list_after_slot (self=0x555555caa330, slot=0x555555e43bd0) at ../src/View/Miller.vala:144
#31 0x00005555555f256b in files_view_miller_nest_slot_in_host_slot (self=0x555555caa330, slot=0x555555ebc550, host=0x555555e43bd0) at ../src/View/Miller.vala:128
#32 0x00005555555f219d in files_view_miller_add_location (self=0x555555caa330, loc=0x555555811320, host=0x555555e43bd0, scroll=1, animate=1) at ../src/View/Miller.vala:103
#33 0x00005555555f4294 in files_view_miller_on_miller_slot_request (self=0x555555caa330, slot=0x555555e43bd0, loc=0x555555811320, make_root=0) at ../src/View/Miller.vala:287
#34 0x00005555555f3aaa in _files_view_miller_on_miller_slot_request_files_view_slot_miller_slot_request
    (_sender=0x555555e43bd0, file=0x555555811320, make_root=0, self=0x555555caa330) at ../src/View/Miller.vala:257
--Type <RET> for more, q to quit, c to continue without paging--
#35 0x00005555555f087f in g_cclosure_user_marshal_VOID__OBJECT_BOOLEAN
    (closure=0x555555e7b950, return_value=0x0, n_param_values=3, param_values=0x7fffffffcf20, invocation_hint=0x7fffffffcea0, marshal_data=0x0) at ../src/View/Slot.vala:21
#36 0x00007ffff7d3b802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007ffff7d4f814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff7d5abbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x00007ffff7d5b0f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#40 0x00005555555ef451 in files_view_slot_on_dir_view_path_change_request (self=0x555555e43bd0, loc=0x555555811320, flag=FILES_OPEN_FLAG_DEFAULT, make_root=0)
    at ../src/View/Slot.vala:235
#41 0x00005555555ee5dd in _files_view_slot_on_dir_view_path_change_request_files_abstract_directory_view_path_change_request
    (_sender=0x555555e585c0, location=0x555555811320, flag=FILES_OPEN_FLAG_DEFAULT, new_root=0, self=0x555555e43bd0) at ../src/View/Slot.vala:116
#42 0x00005555555e4520 in g_cclosure_user_marshal_VOID__OBJECT_ENUM_BOOLEAN
    (closure=0x555555ebef00, return_value=0x0, n_param_values=4, param_values=0x7fffffffd480, invocation_hint=0x7fffffffd400, marshal_data=0x0)
    at ../src/View/AbstractDirectoryView.vala:29
#43 0x00007ffff7d3b802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff7d4f814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x00007ffff7d5abbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff7d5b0f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00005555555c84ac in files_abstract_directory_view_load_location (self=0x555555e585c0, location=0x555555811320) at ../src/View/AbstractDirectoryView.vala:520
#48 0x00005555555ca9b7 in files_abstract_directory_view_activate_file
    (self=0x555555e585c0, _file=0x55555603aaa0, screen=0x5555556bc0a0, flag=FILES_OPEN_FLAG_DEFAULT, only_one_file=1) at ../src/View/AbstractDirectoryView.vala:798
#49 0x00005555555c8a83 in files_abstract_directory_view_activate_selected_items (self=0x555555e585c0, flag=FILES_OPEN_FLAG_DEFAULT, selection=0x55555580aac0 = {...})
    at ../src/View/AbstractDirectoryView.vala:538
#50 0x00005555555b91d0 in files_column_view_not_double_click (self=0x555555e585c0, event=0x555555aa9d00, path=0x555555ac42b0) at ../src/View/ColumnView.vala:57
#51 0x00005555555b98e4 in ____lambda65_ (_data17_=0x555555837b80) at ../src/View/ColumnView.vala:148
#52 0x00005555555b990c in _____lambda65__gsource_func (self=0x555555837b80) at ColumnView.c:787
#53 0x00007ffff7dd9be8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#54 0x00007ffff7dd904e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#55 0x00007ffff7dd9400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#56 0x00007ffff7dd94a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#57 0x00007ffff7c28fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#58 0x0000555555582f1a in _vala_main (args=0x7fffffffddb8, args_length1=1) at ../src/main.vala:26
#59 0x0000555555582f61 in main (argc=1, argv=0x7fffffffddb8) at ../src/main.vala:16
```

Seems to happen on the *second* subfolder selection.
