### ISSUE TITLE
Crash when clicking "Empty the Trash"

### ISSUE THREAD

**Issue by davidak** [elementary/files#2072]
### What Happened?

I had 2 windows open, one with SMB mount from NAS, one with 4 tabs including Trassh. I clicked "Empty the Trash" and it crashed.

### Steps to Reproduce

no possible

### Expected Behavior

no crash

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
(gdb) bt
#0  0x0000000000476bb9 in files_view_overlay_bar_read_image_stream_co.isra ()
#1  0x00007f4c29311eab in async_ready_callback_wrapper (source_object=0x20024a0, res=0x1691330, user_data=0x7f4c0800cc90) at ../gio/ginputstream.c:563
#2  0x00007f4c29345903 in g_task_return_now (task=0x1691330) at ../gio/gtask.c:1230
#3  0x00007f4c293462eb in g_task_return (type=<optimized out>, task=0x1691330) at ../gio/gtask.c:1299
#4  g_task_return (task=0x1691330, type=<optimized out>) at ../gio/gtask.c:1256
#5  0x00007f4c160b385f in async_read_done () from /nix/store/8gdq6q4445q741jlkvdbjysjwdszbzi8-gvfs-1.50.2/lib/gio/modules/libgvfsdbus.so
#6  0x00007f4c160b55b7 in async_iterate () from /nix/store/8gdq6q4445q741jlkvdbjysjwdszbzi8-gvfs-1.50.2/lib/gio/modules/libgvfsdbus.so
#7  0x00007f4c160b5957 in async_read_op_callback () from /nix/store/8gdq6q4445q741jlkvdbjysjwdszbzi8-gvfs-1.50.2/lib/gio/modules/libgvfsdbus.so
#8  0x00007f4c29311eab in async_ready_callback_wrapper (source_object=0x2c8caa0, res=0x1b0f280, user_data=0x2495f80) at ../gio/ginputstream.c:563
#9  0x00007f4c29345903 in g_task_return_now (task=0x1b0f280) at ../gio/gtask.c:1230
#10 0x00007f4c29345939 in complete_in_idle_cb (task=0x1b0f280) at ../gio/gtask.c:1244
#11 0x00007f4c29529d04 in g_main_dispatch (context=0xe2bc00) at ../glib/gmain.c:3417
#12 g_main_context_dispatch (context=0xe2bc00) at ../glib/gmain.c:4135
#13 0x00007f4c2952a0a8 in g_main_context_iterate (context=context@entry=0xe2bc00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:4211
#14 0x00007f4c2952a15f in g_main_context_iteration (context=context@entry=0xe2bc00, may_block=may_block@entry=1) at ../glib/gmain.c:4276
#15 0x00007f4c2937371d in g_application_run (application=0xe40140, argc=<optimized out>, argv=<optimized out>) at ../gio/gapplication.c:2569
#16 0x000000000042f9ff in main ()
```

**Comment by jeremypw** [comment]
The error shown in the backtrace has been reported in another context  - not sure which report number.  There is a PR extant that stops the overlaybar showing on hover which may help but need to ensure that it cannot crash on trying to analyse images it cannot handle.

**Comment by jeremypw** [comment]
The overlay bar no longer shows on hover.  Need a new report related specifically to crashing on showing the properties of image files (after selecting) if this can be reproduced on the latest version.  As far as I can tell this issue is not related to emptying the trash.
