### ISSUE TITLE
Opening a folder with a .desktop file crashes Files

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/files#380]
Started happing after today's update, so it may have being cause by a recent change (Unsure when my last upgrade was)

### How to reproduce:
Just open a folder containing a .desktop file

### GDB backtrace: 

```
(io.elementary.files:27520): Gtk-WARNING **: 21:39:00.533: Allocating size to GtkNotebook 0x555555ca0230 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[New Thread 0x7fffd57ef700 (LWP 27529)]
[New Thread 0x7fffd4fee700 (LWP 27530)]
[New Thread 0x7fffc7fff700 (LWP 27531)]
[New Thread 0x7fffc77fe700 (LWP 27532)]

Thread 1 "io.elementary.f" received signal SIGSEGV, Segmentation fault.
0x00007ffff56efc5d in g_key_file_get_value () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff56efc5d in g_key_file_get_value () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff56efee3 in g_key_file_get_string () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4d80972 in gof_file_update () at /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.0
#3  0x00007ffff4d96633 in  () at /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.0
#4  0x00007ffff77d2a6b in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x00007ffff780afa3 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007ffff780afd9 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007ffff56f7f85 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff56f8350 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff56f83dc in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff7820cbd in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x00007ffff7b3daa9 in granite_application_run () at /usr/lib/x86_64-linux-gnu/libgranite.so.4
#12 0x0000555555581e59 in _vala_main ()
```

**Comment by danrabbit** [comment]
Fixed by #382
