### ISSUE TITLE
Crash when selecting a sole image file by rubberbanding and including point top left corner.

### ISSUE THREAD

**Issue by jlnr** [elementary/files#991]
I'm seeing a reproducible crash when I try to select a single file in a folder via "drag area selection". Edit: This is with a single PNG file in a folder, but I just tried to delete the GIF file attached below, and selecting the GIF file also crashes Files.

![filescrash](https://user-images.githubusercontent.com/70772/61630477-1c30ca00-ac88-11e9-87ad-a5b6b4488c24.gif)

gdb Stacktrace:

```
Thread 1 "io.elementary.f" received signal SIGSEGV, Segmentation fault.
0x00005555555c90f9 in ?? ()
(gdb) backtrace
#0  0x00005555555c90f9 in  ()
#1  0x00007ffff73d710d in g_closure_invoke ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff73ea05e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff73f2715 in g_signal_emit_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff73f312f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff59e539e in  () at /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
#6  0x00007fffc45f65e8 in  ()
    at /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
#7  0x00007fffefb53779 in  () at /usr/lib/x86_64-linux-gnu/libpng16.so.16
#8  0x00007fffefb5455b in png_process_data () at /usr/lib/x86_64-linux-gnu/libpng16.so.16
#9  0x00007fffc45f5d5a in  ()
    at /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
#10 0x00007ffff59e5a84 in gdk_pixbuf_loader_write ()
    at /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
#11 0x00005555555c88f1 in  ()
#12 0x00007ffff708c57a in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x00007ffff70b51a3 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x00007ffff70b51d9 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007ffff7667285 in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff7667650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff76676dc in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff70cae3d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#19 0x000055555557afe7 in _vala_main ()
#20 0x00007ffff49a5b97 in __libc_start_main (main=
    0x55555557ae60 <main>, argc=1, argv=0x7fffffffdd88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdd78) at ../csu/libc-start.c:310
#21 0x000055555557ae9a in _start ()
```

Sorry, I have no time to dig into this myself today :)

**Comment by jeremypw** [comment]
Thanks for the report. This crash is associated with dragging to select the point (0, 0), it seems.  If you stop the rubberband selection short of this point (i.e. within the file item) no crash occurs.  I'll look into it further and try to fix.
